### ISSUE TITLE
Strange issue with the example.

### ISSUE THREAD

**Issue by iguron** [AMArostegui/SpacyDotNet#5]
Hola Antonio,

First of all, let you know that I have no idea of Python, but using spacyDotNet, I found really easy to use space in my .net project.

I build a .net app, (WinForms) using spacydotnet and I'm having an strange issue. If I run the app from VS (with F5), it works with no problem. But If I try to use the build .exe it fails always with 'AttributeError : 'NoneType' object has no attribute 'flush''

I tried in a W7 or W10 machine, both 64bits. I tried with python 3.7.0 and 3.7.1

In order to locate the problem, I took the test project from spacydotnet and I found that setting output of the project as Console app works fine, but If I tried changing the output type to windows Application, I get the same error loading the model ("var nlp = spacy.load(pyString);")

I believe this is related with the output of the python.net, could it be?

Any suggestion or trick?

thanks in advance.

**Comment by AMArostegui** [comment]
From the beginning, portability was a concern when developing the library, as I plan to run my software on a Linux Server.

So I decided to go with .NET Core because of that and because it is the future of .NET according to MS (.NET 5)

So I hadn't even tried a .NET Framework setup. As your program is WinForms, I guess it's running on .NET Framework.

It is possible to use a .NET Standard 2.0 library in a .NET Framework program. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard And indeed it is as I have done this in the past.

So, theoretically, is should be possible to run SpacyDotNet in a WinForms .NET Framework 4.6.1 program, as both SpacyDotNet and Python.NET are .NET Standard 2.0 libraries. Sadly, I've tried but didn't find success.

Luckily, WinForms is now available on .NET 5, and the library works sucesfully under this configuration.

**Comment by iguron** [comment]
Hi Antonio, thanks for the quick reply. At last I found what was the problem.

Redirecting stdout and stderr before language load solve the problema.

public Lang Load(string model)
        {
            using (Py.GIL())
            {
                string redirectOutput =
                "import sys\n" +
                "from io import StringIO\n" +
                "sys.stdout = mystdout = StringIO()\n" +
                "sys.stdout.flush()\n" +
                "sys.stderr = mystderr = StringIO()\n" +
                "sys.stderr.flush()\n";

                //Para redirigir el stdout
                PythonEngine.RunString(redirectOutput);

                dynamic spacy = Py.Import("spacy");
                var pyString = new PyString(model);
                var nlp = spacy.load(pyString);
                return new Lang(nlp);
            }
        }
